# Generated by Django 3.0.8 on 2020-07-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_fair', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucements',
            new_name='Announcement',
        ),
    ]
