# Generated by Django 3.0.8 on 2020-07-24 16:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='tech_fair/images/')),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('education_level', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior'), (5, 'Graduate')], max_length=5)),
                ('major', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Computer Animation & Game Development'), (2, 'Civil Engineering'), (3, 'Computer Information Systems'), (4, 'Computer Science'), (5, 'Construction Industry Management'), (6, 'Concrete Industry Management'), (7, 'Contstruction Management'), (8, 'Electrical Engineering'), (9, 'Mechanical Engineering'), (10, 'Mechatronic Engineering'), (11, 'Sustainable Manufacturing')], max_length=11)),
            ],
        ),
    ]
