# Generated by Django 3.0.8 on 2020-08-02 00:23

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='major',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Computer Animation & Game Development'), (2, 'Civil Engineering'), (3, 'Computer Engineering'), (4, 'Computer Information Systems'), (5, 'Computer Science'), (6, 'Construction Industry Management'), (7, 'Concrete Industry Management'), (8, 'Contstruction Management'), (9, 'Electrical Engineering'), (10, 'Mechanical Engineering'), (11, 'Mechatronic Engineering'), (12, 'Sustainable Manufacturing')], max_length=12),
        ),
    ]
