# Generated by Django 3.0.8 on 2020-08-06 22:09

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20200802_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='registerer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='education_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior'), (5, 'Graduate'), (6, 'Working Experience')], max_length=6),
        ),
    ]
